game like cv - wip
outbrain/cv-boostifier pull request #10
Opened 2020-10-22 08:56 UTC by yonbav

We added alot of assets. 
We are still working on it and plan to work on it, but all unused assets will be removed when we are done.

2020-11-12 13:44 UTC, tsachis reviewed
I'll merge it manually as there is some conflicts and you touched some file outside of the skin folder

2020-12-13 10:04 UTC, dsternlicht requested changes

2020-12-13 10:04 UTC, dsternlicht commented on src/index.scss
>  body {
I don't like that all of these changes are on the main `index.scss` file. They might affect all other skins. Can this be scoped to your skin only?

2020-12-13 10:04 UTC, dsternlicht commented on src/models.ts
>    /**
@tsachis Can you please review?

2020-12-16 14:00 UTC, closed without merging

2020-12-16 14:01 UTC, tsachis commented
already merged it manually