Comix skin
outbrain/cv-boostifier pull request #9
Opened 2020-10-22 08:04 UTC by asafcode

2020-10-22 08:39 UTC, dsternlicht requested changes

2020-10-22 08:39 UTC, dsternlicht commented on src/amy.profile.json
> +{
Can you remove this file?

2020-10-22 08:39 UTC, dsternlicht commented on src/amy.profile.json
> +{
Is it needed?

2020-10-22 08:39 UTC, dsternlicht commented on package.json
> +    "cloudinary-react": "^1.6.7",
Are you using this dependency? If not, can you please uninstall it?

2020-11-12 13:49 UTC, tsachis approved these changes

2020-11-12 13:49 UTC, merged